# Generated by Django 3.2 on 2021-04-06 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shower_head',
            field=models.CharField(choices=[('normal', 'Normal shower head'), ('efficient', 'Efficient shower head')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='swimming_pool',
            field=models.CharField(choices=[('none', 'No pool'), ('small', 'Small pool'), ('medium', 'Medium pool'), ('large', 'Large pool')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='washer_type',
            field=models.CharField(choices=[('top', 'Top-load washer'), ('front', 'Front-load washer')], max_length=30),
        ),
    ]
